### PR TITLE
Explain 420 joke

### PR DESCRIPTION
**Pull request by expectocode**

### CODE REVIEW

**Comment by udf** [comment]
no

**Comment by Lonami** [comment]
@udf why are you hiding the truth?

**Comment by udf** [comment]
/\
     /𓂀\
    ------

**Comment by expectocode** [comment]
```                    *
                   ***
                  *****
                 *******
                *********
               ***********
              *************
             ***************
            *****************
           *******************
          *********************
         ***********************
        *************************
       ***************************
      *****************************
     *******************************
    *********************************
   ***********************************
  *************************************
 ***************************************
*****************************************
               
I    L    L    U    M    I    N    A    T    I

**Comment by udf** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⢿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡹⢿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡚⣼⡹⣻⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⢻⠂⢻⠂⢻⢌⢟⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠛⠃⠓⠀⠀⠀⠀⢕⢟⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⠀⢠⡟⡷⣤⣻⢛⡛⣟⡯⡿⣬⡻⡄⠀⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⠀⢠⢻⠋⠛⠒⠀⠀⠀⠀⠀⠃⠛⠚⠛⡄⠀⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⠀⢠⢻⠱⣤⠛⠑⠉⠙⠑⡹⡸⡠⢤⠀⠀⢟⡄⠀⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⠀⢠⠛⠓⡄⡤⣤⣤⣤⣤⣤⣤⣤⠀⠃⣭⡛⣤⠛⡄⠀⠀⠀⠀⠀
    ⠀⠀⠀⠀⢠⠻⣧⣧⣿⣿⣻⣻⠀⠀⠀⢽⢿⢿⣿⣤⣿⣤⢝⢿⡄⠀⠀⠀⠀
    ⠀⠀⠀⢠⣿⣿⣿⠀⠀⠀⠓⢯⢯⣟⡽⣯⠛⠀⠀⠀⠛⣿⣵⣵⡻⡄⠀⠀⠀
    ⠀⠀⢠⡻⡸⠀⣟⠀⠀⠀⠀⠀⠛⠚⠙⠀⠀⠀⠀⠀⠀⠛⠛⡻⡪⡻⡄⠀⠀
    ⠀⢠⢻⢸⢠⠀⢄⠓⠀⢤⠀⠀⠀⠀⠀⡀⠀⠀⣄⠙⠘⠀⡤⠘⣤⢪⢿⡄⠀
    ⢠⣿⣣⠛⡤⣼⠀⣷⡠⢤⠀⠋⠉⠙⠑⠑⠙⠘⡄⠄⢤⠱⣤⡓⣬⠳⣵⣻⡄
    ⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛

**Pull request closed without merging**
